export const BY_VOTE_HIGHEST = 'BY_VOTE_HIGHEST'
export const BY_VOTE_LOWEST = 'BY_VOTE_LOWEST'
export const BY_MODIFIED_EARLIEST = 'BY_MODIFIED_EARLIEST'
export const BY_MODIFIED_LATEST = 'BY_MODIFIED_LATEST'
